# Generated by Django 6.0.2 on 2026-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism va Familiya')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board_members/', verbose_name='Rasm')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Rasm URL (ixtiyoriy)')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Viloyat')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rinsin")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Kengash a'zosi",
                'verbose_name_plural': "Kengash a'zolari",
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Rasm')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Rasm URL (ixtiyoriy)')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Rasm URL (ixtiyoriy)')),
                ('category', models.CharField(choices=[('talim', "Ta'lim"), ('yigilish', "Yig'ilish"), ('hamkorlik', 'Hamkorlik'), ('boshqa', 'Boshqa')], default='boshqa', max_length=50, verbose_name='Kategoriya')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilingan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExamSession',
        ),
    ]
